const data = {
    products: [
        {
            _id:'1',
            name: 'Maria',//name:'Polo sin mangas seamless activa vania',
            category: 'Polos',
            image:'/images/p1.jpg',
           // price: 79.95,
            brand: 'MARQUIS',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality',
        },
        {
            _id:'2',
            name: 'Maria',//name:'Polo sin mangas activa bala',
            category: 'Polos',
            image:'/images/p2.jpg',
           // price: 79.95,
            brand: 'Marquis',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality',
        },
        {
            _id:'3',
            name: 'Nicole',//name:'Polo manga 3/4 alicia',
            category: 'Polos',
            image:'/images/p3.jpg',
           // price: 49.95,
            brand: 'Marquis',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality',
        },
        {
            _id:'4',
            name: 'Brenda',//name:'Polo manga 3/4 croacia',
            category: 'Polos',
            image:'/images/p4.jpg',
            //price: 41.95,
            brand: 'Marquis',
            rating: 4.0,
            numReviews: 10,
            description: 'High Quality',
        },
        {
            _id:'5',
            name: 'Fiorella',//name:'Top Efiorella',
            category: 'Polos',
            image:'/images/p5.jpg',
            //price: 19.95,
            brand: 'Marquis',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality',
        },
        {
            _id:'6',
            name: 'Lucia',//name:'Polo Manga Larga Achispa',
            category: 'Polos',
            image:'/images/p6.jpg',
           // price: 59.95,
            brand: 'Marquis',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality',
        }
    ],
}

export default data;